server:
  port: 8081

spring:
  application:
    name: Auth

  datasource:
    url: jdbc:mysql://localhost:4306/spring_boot_auth_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG